server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cesi?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      max-lifetime: 600000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.cesi.datalogscheduler.mapper: DEBUG
    org.springframework.web: DEBUG
    org.mybatis.spring: DEBUG
    java.sql: DEBUG
  config: classpath:log4j2-spring.xml
conflict:
  local-path: /usr/local/share/cesi/backup/data # 文件冲突保存本地路径
  volume-path: E:/Workspaces/cesi/backup/data   # 文件冲突保存挂载路径
schedule:
  default-cron: 0 30 8 * * *                    # 默认定时
  task-timeout: 60                              # 任务超时时长
  compression-level: 6                          # 压缩级别
  zip-split-size: 0x40000000                    # 分卷大小
cors-filter:
  access-control-allow-origin: http://localhost:8083
udp:
  port:
    log: 9001